#!/usr/bin/env python
import forecastio
import subprocess
from slacker import Slacker
from properties import slack_token

slack = Slacker(slack_token)

forecast_key = "be063e11c53854ceb6e27afed0057aec"
lat = "37.5000327"
lng = "-77.5628374"


forecast = forecastio.load_forecast(forecast_key, lat, lng)
byDay = forecast.daily()
w = ""

print "-------------------------- DAILY --------------------------"
for dailyData in byDay.data:
    wind = dailyData.windSpeed
    time = dailyData.time
    wind_message = "Wind is expected to be " + str(wind) + "mph on " + str(time.strftime("%A\n"))

    if wind > 8:
        w += wind_message

slack.chat.post_message('#sandbox', w)
